### ISSUE TITLE
Steps should automatically progress to next upon success

### ISSUE THREAD

**Issue by solvingj** [karfunkel/glow#4]
It seems that the code already executes the setup and cleanup actions for the next step, but for some reason skips the "action" closure. 

I would say that the default should be to do next() after success.   

Besides next() it seems like there are an overwhelming other of other options one might want to execute. For example, exit the script, go back X steps, redo X times, some sort of "GoTo" logic which could name a step at any other level, a GPath expression relative to the parent/child relationship of steps.  To override, the implementer would need to be aware of all the options, and need docs on implementation, etc.

**Comment by solvingj** [comment]
Also, currently, calling next() on the last step results in error: 

java.lang.NullPointerException: Cannot get property 'id' on null object

```
at com.gsi.genius.jde.app.Script1$_run_closure1.closure2$_closure6(Script1.groovy:25)
at com.gsi.genius.jde.app.Script1$_run_closure1.closure2$_closure6(Script1.groovy)
at org.aklein.glow.Step.runClosure(Step.groovy:104)
at org.aklein.glow.Step.onEvent(Step.groovy:116)
at org.aklein.glow.Step.call(Step.groovy:66)
at org.aklein.glow.Glow.start(Glow.groovy:39)
at com.gsi.genius.jde.app.Script1.run(Script1.groovy:69)
at com.gsi.genius.jde.app.DatasourceShell.run(DatasourceShell.groovy:13)
at com.gsi.genius.jde.app.DatasourceShellSpec.Will DiscoveryScript be called?(DatasourceShellSpec.groovy:30)
```

**Comment by karfunkel** [comment]
Should be fixed now - please create a testcase and test it :)
